name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare out directory
        run: |
          rm -rf out || true
          mkdir out
          rsync -av --exclude='.git' --exclude='.github' --exclude='node_modules' ./ out/

      - name: Deploy to Pages
        uses: actions/deploy-pages@v1
        with:
          folder: ./out
